from enum import StrEnum


class Channel(StrEnum):
    EMAIL = "EMAIL"
    SUPPORT_CHAT = "SUPPORT_CHAT"
    WHATSAPP = "WHATSAPP"
    INTERNAL_NOTE = "INTERNAL_NOTE"


class IncidentType(StrEnum):
    FUNCTIONAL_FAILURE = "FUNCTIONAL_FAILURE"
    DAMAGED_ON_ARRIVAL = "DAMAGED_ON_ARRIVAL"
    WRONG_ITEM = "WRONG_ITEM"
    MISSING_ITEM = "MISSING_ITEM"


class RemedyType(StrEnum):
    CASH_REFUND = "CASH_REFUND"
    REPLACEMENT = "REPLACEMENT"
    STORE_CREDIT = "STORE_CREDIT"


class IncidentRelation(StrEnum):
    SAME_INCIDENT = "SAME_INCIDENT"
    NEW_INCIDENT = "NEW_INCIDENT"
    PARTIALLY_OVERLAPPING = "PARTIALLY_OVERLAPPING"
    UNCERTAIN = "UNCERTAIN"


class Decision(StrEnum):
    ALLOW = "ALLOW"
    REVIEW = "REVIEW"
    PREVENT_DUPLICATE = "PREVENT_DUPLICATE"


class RemedyStatus(StrEnum):
    PROPOSED = "PROPOSED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    RESERVED = "RESERVED"
    PROCESSING = "PROCESSING"
    SETTLED = "SETTLED"
    FAILED = "FAILED"
    RELEASED = "RELEASED"
    CANCELLED = "CANCELLED"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"


class Currency(StrEnum):
    INR = "INR"


class ReasonCode(StrEnum):
    NEW_INCIDENT = "NEW_INCIDENT"
    SAME_INCIDENT = "SAME_INCIDENT"
    PARTIALLY_OVERLAPPING = "PARTIALLY_OVERLAPPING"
    UNCERTAIN_LINK = "UNCERTAIN_LINK"
    ENTITLEMENT_AVAILABLE = "ENTITLEMENT_AVAILABLE"
    ENTITLEMENT_EXHAUSTED = "ENTITLEMENT_EXHAUSTED"
    ENTITLEMENT_EXCEEDED = "ENTITLEMENT_EXCEEDED"
    RESERVATION_HELD = "RESERVATION_HELD"
    CONTRADICTION = "CONTRADICTION"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    IDEMPOTENT_REPLAY = "IDEMPOTENT_REPLAY"


class AuditEventType(StrEnum):
    WORLD_INGESTED = "WORLD_INGESTED"
    ATTEMPT_INGESTED = "ATTEMPT_INGESTED"
    ATTEMPT_REPLAYED = "ATTEMPT_REPLAYED"
    REFUND_REQUESTED = "REFUND_REQUESTED"
    REFUND_SETTLED = "REFUND_SETTLED"
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    WEBHOOK_DUPLICATE = "WEBHOOK_DUPLICATE"
    CLAIM_COMPILED = "CLAIM_COMPILED"
    CLAIM_REPLAYED = "CLAIM_REPLAYED"

class MatchReason(StrEnum):
    SAME_CUSTOMER = "SAME_CUSTOMER"
    ORDER_REFERENCE_MATCH = "ORDER_REFERENCE_MATCH"
    SHARED_DESCRIPTION_TOKENS = "SHARED_DESCRIPTION_TOKENS"
    INCIDENT_TYPE_MATCH = "INCIDENT_TYPE_MATCH"
    PRIOR_REMEDY_EXISTS = "PRIOR_REMEDY_EXISTS"
